# Generated by Django 5.1.3 on 2024-11-17 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="users_posts",
        ),
    ]
